### ISSUE TITLE
Update PSP Allows Privilege Escalation query for Kubernetes

### ISSUE THREAD

**Issue by jonny-wg2** [Checkmarx/kics#3395]
### Platform
Kubernetes

### Description
false positive as privilege is set as false

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/39831372/118990133-e8f21b80-b982-11eb-8087-bb445453229d.png">

**Comment by felipe-avelar** [comment]
@jonny-wg2 Hello and thank you for your report.
I think this is not a false positive, since the pod still can have `CAP_SYS_ADMIN` enabled and, as you can see [here](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/), if `privileged` **or** `CAP_SYS_ADMIN` is true, `allowPrivilegeEscalation` will be set to `true`.

**Comment by jonny-wg2** [comment]
Gotcha, thanks for your clarification. Closing ticket.
