### ISSUE TITLE
Allow users to ignore specific lines during kics-scan

### ISSUE THREAD

**Issue by LvffY** [Checkmarx/kics#4420]
**Describe the solution you'd like**

**Kics** already allow users to [disable scan on whole files](https://docs.kics.io/latest/running-kics/#using_commands_on_scanned_files_as_comments). But for most cases, I think it would be more useful to just ignores **lines of files** and not the entire file.

From a security point of view, it's not because one line on my file could not be analysed that I want to exclude the rest of my file (that could hide some more security breaches).

**Additional context**

It could be useful for temporary issues and/or too specific context problem (could probably solve #4419)

**Comment by joaoReigota1** [comment]
Regarding this issue this is the approach we are thinking of:

Users would be able to use two comments as commands in order to ignore specific lines
 - kics ignore-block
 - kics ignore-line

#### kics ignore-block

This command ignores the object and all its key-value pairs beneath the line of the command

#### kics ignore-line

This command ignores the line beneath the line of the command

### Dockerfile

![image](https://user-images.githubusercontent.com/74597872/140167241-1bf945ac-66dd-4673-b092-0153f1328329.png)

- line 6 is ignored from the comment on line 5
- line 10, 11 are ignored from the comment on lines 9
- line 15, 16, 17, 18 (whole from the block) are ignored from the comment on lines 14

### Terraform

![image](https://user-images.githubusercontent.com/74597872/140168332-ffbfca25-8ae1-4611-947d-01868b2f83fa.png)

- lines 4, 5, 6 are ignored from the comment on line 3
- lines 11, 12, 13 are ignored from the comments on line 10
- line 18 is ignored from the comment on line 17

### YAML

 
![image](https://user-images.githubusercontent.com/74597872/140169049-16665b98-11b7-4261-9d94-02af2e621c2a.png)

- lines 4, 5 are ignored from the comment on lines 3
- line 11 is ignored from the comment on lines 10
- lines 17, 18, 19 are ignored from the comment on lines 16
- lines 22, 23, 24, 25 are ignored from the comment on lines 21

### JSON

It is not possible to add this feature since JSON files don't support comments

**Comment by LvffY** [comment]
@joaoReigota1 It would be great !

**Comment by balq60** [comment]
This does not work:

Tried this:

// kics ignore-block
resource "aws_s3_bucket" "bucket" {
  #checkov:skip=CKV_AWS_144:This bucket is not required to have cross-region replication enabled because it only contains test data.
  count               = local.create_bucket ? 1 : 0
  bucket              = var.bucket_name
  force_destroy       = var.force_destroy
  object_lock_enabled = var.object_lock_enabled
}

#######################
# Log Bucket creation #
#######################
// kics ignore-block
resource "aws_s3_bucket" "log_bucket" {
  #checkov:skip=CKV_AWS_144:This bucket is not required to have cross-region replication enabled because it only contains test data.
  count  = local.create_bucket ? 1 : 0
  bucket = var.log_bucket_name
}

Tried this:

###################
# Bucket creation #
###################
#kics ignore-line
resource "aws_s3_bucket" "read_only_bucket" {
  #checkov:skip=CKV_AWS_144:This is too aggressive for most cases.  This should depend on the data being stored.
  #kics ignore-line
  bucket = var.bucket_name_read_only
}

#######################
# Log Bucket creation #
#######################
#kics ignore-line
resource "aws_s3_bucket" "read_only_log_bucket" {
  #checkov:skip=CKV_AWS_144:This is too aggressive for most cases.  This should depend on the data being stored.
  #kics ignore-line
  bucket = var.log_bucket_name_read_only
}

Still shows up in report

**Comment by boatilus** [comment]
@balq60 The comment needs to start with `kics-scan`, not `kics`. See https://github.com/Checkmarx/kics/blob/master/docs/running-kics.md
