### ISSUE TITLE
Update Vulnerable Default SSL Certificate query for Terraform

### ISSUE THREAD

**Issue by zbmowrey** [Checkmarx/kics#4577]
### Platform
*Terraform*

### Provider
*AWS*

### Description
This query returns results when it should not. Example configurations that result in a report: 

    viewer_certificate {
        cloudfront_default_certificate = false
        acm_certificate_arn            = aws_acm_certificate.web-cert.arn
        ssl_support_method             = "sni-only"
  }

and

    viewer_certificate {
        acm_certificate_arn = var.acm-certificate-arn
        ssl_support_method  = "sni-only"
    }

![image](https://user-images.githubusercontent.com/14931610/144459856-ae62bf14-c8b5-4832-8d57-c0d6d5ec67ee.png)

After receiving the result on the first case, I tried omitting the default certificate value. In both cases, the query still reports reliance on the default cert, even when I'm specifying the acm_certificate_arn value.

**Comment by rafaela-soares** [comment]
Hello, @zbmowrey 🙂 I hope this message finds you well.

Thank you so much for reaching us. We will take a look!

**Comment by rafaela-soares** [comment]
Hi, @zbmowrey! I hope you are doing well.

This query also requires the definition of `minimum_protocol_version`. That's why it is reporting a result.

You can observe the KICS suggestion in the `expected_value` of the output (`kics scan -p <project-path> -o <outputPath>`). 


As an example:
![result](https://user-images.githubusercontent.com/74001161/146577315-7bc0b6e2-4b9d-43cb-83a0-1500a6caf458.PNG)

**Comment by rafaela-soares** [comment]
Hi @zbmowrey 🙂

I am going to close this issue due to inactivity. I hope my explanation has helped you. Meanwhile, you can always open a new issue if you desire.
