### ISSUE TITLE
Check any simple yaml file

### ISSUE THREAD

**Issue by jycamier** [Checkmarx/kics#4860]
## My problem

I would like to check some attributes in YAML files (a github action pipeline in my context) which are mandatory. So, I've created a query for that but it seam that's not possible : my files are parsed but nothing happen.

Is it possible to create a query which fit on any yaml ?
How ?

**Comment by rafaela-soares** [comment]
Hello, @jycamier 🙂 I hope you are well.

When a YAML sample is not a CloudFormation, Google Deployment Manager, Helm, Kubernetes or OpenAPI sample, KICS recognize it as Ansible (because KICS does not support a robust approach to identifying Ansible samples).

So, your GitHub action pipeline is parsed because it is interpreted as Ansible (without the use of the flag `-t`). However, it could be parsed as well if you pointed to a platform that supports YAML as an extension in flag `-t`. For example, `kics scan -p <file.yaml> -q <your-query-path> -t ansible` or `kics scan -p <file.yaml> -q <your-query-path> -t cloudFormation`.

If you want to run a query against your GitHub action pipeline (without the use of the flag `-t`), you should set `"platform": "Ansible"` in the query metadata, as well as a random cloudProvider (because the GitHub action pipeline is recognized as Ansible). To use your query, you should pass the query path in `-q` or `--queries-path`. 

If you want to run a query against your GitHub action pipeline (with the the use of the flag `-t`, for example `kics scan -p <file.yaml> -q <your-query-path> -t cloudFormation`),  you should set `"platform": "CloudFormation"` and `cloudProvider: "aws"` in the query metadata. With `-t cloudFormation`, KICS will run all the cloudFormataion queries found.

In the next release, it will work with `"platform": "Common"`. PR #4862 fixes a bug related to common queries usage.

Note that this is just a workaround. Let me know if it worked, please 😊

**Comment by jycamier** [comment]
Thank you so much @rafaela-soares for you answer. I check it now.

**Comment by jycamier** [comment]
Excellent ! 
That works. However, the incriminated code is not displayed but for a temporary workaround it is sufficient.

**Comment by rafaela-soares** [comment]
Great, @jycamier 🙂  What do you mean by "the incriminated code is not displayed"?

**Comment by jycamier** [comment]
I speak about the block a code concerned by the query.

![image](https://user-images.githubusercontent.com/984570/155017433-0cf023c4-8b0c-490d-b16e-47927bdf2e06.png)

The query is very simple.

```yaml
name: matrix-test
on:
  pull_request: {}
jobs:
  matrix-fail:
    strategy:
      max-parallel: 8
      matrix:
        - name: titi
        - name: toto
    runs-on: [self-hosted, linter]
    steps:
      - uses: actions/checkout@v2
  matrix-ok:
    strategy:
      max-parallel: 7
      matrix:
        - name: titi
        - name: toto
    runs-on: [self-hosted, linter]
    steps:
      - uses: actions/checkout@v2
```

```rego
package Cx

import data.generic.common as common_lib

CxPolicy[result] {
    job := input.document[i].jobs[name]

    common_lib.valid_key(job.strategy, "matrix")
    not common_lib.valid_key(job.strategy, "max-parallel")

    result := {
        "documentId": input.document[i].id,
        "searchKey": sprintf("jobs[{{%s}}].strategy", [name]),
        "issueType": "MissingAttribute",
        "keyExpectedValue": sprintf("jobs[%s].strategy.max-parallel is set and not null", [name]),
        "keyActualValue": sprintf("jobs[%s].strategy.max-parallel is missing or null", [name]),
    }
}

CxPolicy[result] {
    job := input.document[i].jobs[name]

    common_lib.valid_key(job.strategy, "matrix")
    common_lib.valid_key(job.strategy, "max-parallel")
    job.strategy["max-parallel"] > 7

    result := {
        "documentId": input.document[i].id,
        "searchKey": sprintf("jobs[{{%s}}].strategy", [name]),
        "issueType": "IncorrectValue",
        "keyExpectedValue": sprintf("jobs[%s].strategy.max-parallel must be less or equal to 7", [name]),
        "keyActualValue": sprintf("jobs[%s].strategy.max-parallel is equal to %d", [name, job.strategy["max-parallel"]]),
    }
}

```

But finaly, I've found how to get something like that : 

![image](https://user-images.githubusercontent.com/984570/155018925-11403ec0-53bb-42a3-87c2-b0af1c02af8b.png)

I've just added  `"searchLine": common_lib.build_search_line(["jobs", name, "strategy"], [])` but honnestly, I need more docs to understand why it works now and why sometimes, the `searchLine` isn't used.

**Comment by rafaela-soares** [comment]
There is a brief documentation about `searchLine` [here](https://github.com/Checkmarx/kics/blob/master/docs/creating-queries.md#search-line). 

Sometimes, `searchKey` and `searchLine` point to the same line, which is the case of your example. However, there are cases where `searchLine` can be more specific than `searchKey`.

For example, if you want to point to a key inside an array, `searchLine` will be more specific than `searchKey` because it is prepared to interpret the indexes of an array and `searchKey` is not.

**Comment by jycamier** [comment]
Okay, very clear @rafaela-soares 
thank your

**Comment by rafaela-soares** [comment]
My pleasure! Feel free to contact us 😊

**Comment by rafaela-soares** [comment]
Hi, @jycamier!

In the latest release (v1.5.3) you can use `"platform": "Common"` in the `metadata.json` of your custom query.

Do you have further questions?

**Comment by jycamier** [comment]
Hi @rafaela-soares. Excellent news. I’ll Check it tomorrow and I close this issue now

**Comment by TmmmmmR** [comment]
> Hello, @jycamier 🙂 I hope you are well.
> 
> When a YAML sample is not a CloudFormation, Google Deployment Manager, Helm, Kubernetes or OpenAPI sample, KICS recognize it as Ansible (because KICS does not support a robust approach to identifying Ansible samples).
> 
> So, your GitHub action pipeline is parsed because it is interpreted as Ansible (without the use of the flag `-t`). However, it could be parsed as well if you pointed to a platform that supports YAML as an extension in flag `-t`. For example, `kics scan -p <file.yaml> -q <your-query-path> -t ansible` or `kics scan -p <file.yaml> -q <your-query-path> -t cloudFormation`.
> 
> If you want to run a query against your GitHub action pipeline (without the use of the flag `-t`), you should set `"platform": "Ansible"` in the query metadata, as well as a random cloudProvider (because the GitHub action pipeline is recognized as Ansible). To use your query, you should pass the query path in `-q` or `--queries-path`.
> 
> If you want to run a query against your GitHub action pipeline (with the the use of the flag `-t`, for example `kics scan -p <file.yaml> -q <your-query-path> -t cloudFormation`), you should set `"platform": "CloudFormation"` and `cloudProvider: "aws"` in the query metadata. With `-t cloudFormation`, KICS will run all the cloudFormation queries found.
> 
> In the next release, it will work with `"platform": "Common"`. PR #4862 fixes a bug related to common queries usage.
> 
> Note that this is just a workaround. Let me know if it worked, please 😊

I'm trying to achieve the same goal but for a JSON files. Is it possible to create a query which fit on any JSON file ? How ?

Thanks

**Comment by barryib** [comment]
I do feel like this issue is not completed. Kics has added Github actions support https://github.com/Checkmarx/kics/pull/6664 but that doesn’t sole the initial issue asking for a way to scan any type of yaml (or json) file. In my case, by exemple, I'm trying to scan Gitlab-CI file with either `CICD` or `Common` platform, but no queries have been loaded.

cc @rafaela-soares @jycamier

**Comment by jycamier** [comment]
@barryib Could you share more information about your issue ?

the kics command ?
the query you write ?
the file you want to scan ?
the kics version ?

**Comment by gabriel-cx** [comment]
Hi @TmmmmmR @barryib @jycamier @LirycR ,

Thank you all for your inputs!

In the past, KICS was able to scan any kind of YAML file, but it was a bug. KICS recognized those files as Ansible, when they, in reality, were not Ansible. And that bug was fixed. That's why you have some old KICS versions with the 'ability' of scanning "any YAML file".

Now, KICS only scans YAML and JSON files if those files content is one of the [supported platforms](https://docs.kics.io/latest/platforms/). Otherwise, the file will be ignored, therefore, not scanned.

If you want to see KICS being able to scan new technologies or having a new feature, feel free to open a feature request. Our Product team will analyze it carefully.

Hope this clarifies your doubts. Feel free to ping us any time!
