### ISSUE TITLE
configuration file as argument doesn't work

### ISSUE THREAD

**Issue by ALutchko** [Checkmarx/kics#5054]
### Expected Behavior
config file mentioned in the command line is used 

### Actual Behavior
Error: initialization error - open kics.config: no such file or directory

### Steps to Reproduce the Problem
Use AWS CodeBuild, the commands/ CodeBuild logs  are as follows:

```
[Container] 2022/03/25 18:23:21 Running command pwd
/codebuild/output/src424192312/src # this is is the repo root

[Container] 2022/03/25 18:23:21 Running command ls -l # checking the file exists in the current dir 
total 8056
...  
-rw-rw-r-- 1 root root     247 Mar 25 18:20 kics.config
...

[Container] 2022/03/25 18:23:21 Running command docker run -v $(pwd):/path $kics_img_name scan --no-progress --ignore-on-exit all -p /path -o /path --report-formats junit --output-name kics-report --config kics.config
Unable to find image 'checkmarx/kics:v1.5.4' locally
v1.5.4: Pulling from checkmarx/kics
Digest: sha256:628ed3b084e6ace14838b2772bf261187a606066d7bb31ed77087beb66ed0847
Status: Downloaded newer image for checkmarx/kics:v1.5.4
Error: initialization error - open kics.config: no such file or directory
Usage:
  kics scan [flags]

Flags:
...
 
```

**Comment by joaoReigota1** [comment]
Hi @ALutchko, 
I am happy to help you
I believe your command might be incorrect, when you create the `PWD` volume it is placed inside `/path`
When you are trying to pass the `kics.config`, you are looking inside the home directory of the container and not the volume, returning correctly that the file does not exist.

This should fix your issue
```sh
docker run -v $(pwd):/path $kics_img_name scan --no-progress --ignore-on-exit all -p /path -o /path --report-formats junit --output-name kics-report --config /path/kics.config 
```

On the other hand, since you are scanning the `/path` where the kics.config is present you don't need to pass the `--config` flag since KICS will know to use the configuration file
For more information: https://docs.kics.io/latest/configuration-file/#configuration_as_code

Hope this helps,
João Reigota

**Comment by ALutchko** [comment]
Hi @joaoReigota1 , thank you very much. Perhaps the doc isn't clear enough. Please close the ticket and thank you again.
