### ISSUE TITLE
Vulnerability is ignored unexpectedly

### ISSUE THREAD

**Issue by ayala-orca** [Checkmarx/kics#6150]
### Expected Behavior

Scanning [this file](https://github.com/bridgecrewio/terragoat/blob/master/terraform/aws/lambda.tf) using kics should list "Hardcoded AWS Access Key In Lambda" vulnerability as part of the results.

### Actual Behavior

"Hardcoded AWS Access Key In Lambda" vulnerability is ignored and not shown as part of the results

Deletion of the [comment on line 32](https://github.com/bridgecrewio/terragoat/blob/master/terraform/aws/lambda.tf#L32) fixes the issue.

### Steps to Reproduce the Problem

1. Run the following command
`docker run -t -v <path-to-terragoat-project>/terraform/aws:/path checkmarx/kics:latest scan -p /path`
"Hardcoded AWS Access Key In Lambda" is not listed as part of the output

2. Delete the [comment on line 32](https://github.com/bridgecrewio/terragoat/blob/master/terraform/aws/lambda.tf#L32) in `lambda.tf`

3. Run the following command again
`docker run -t -v <path-to-terragoat-project>/terraform/aws:/path checkmarx/kics:latest scan -p /path`
Now "Hardcoded AWS Access Key In Lambda" is listed as expected

**Comment by lior-orca** [comment]
@cxMiguelSilva is anyone from the team given it a look?

**Comment by rjegoncalves** [comment]
Hi @ayala-orca,

Thank you for sharing this with us. I did a quick debug and came to the same result as you. Miguel (@cxMiguelSilva) or someone from his team are the most suitable ones to help with this.
One point I leave here is that despite this issue with the _Hardcoded AWS Access Key In Lambda_ rule, the problem is correctly identified in the _[Passwords and Secrets](https://docs.kics.io/latest/secrets/) - AWS Access Key_ rule.

**Comment by cxMiguelSilva** [comment]
Hi @lior-orca and @ayala-orca,
We already took an initial look at this issue. The problem resides somewhere in our Terraform parser and is not related to the rego queries. Thank you @rjegoncalves for the quick response and insights regarding this issue.
I will update this thread once we solve the bug.

**Comment by cxMiguelSilva** [comment]
Hi @lior-orca and @ayala-orca, 
I am glad to let you know that this issue is being solved in #6170. The problem resided in the search key being unable to detect the vulnerability's correct location. Sorry for the misleading information in the previous comment.
Thank you so much for reporting this bug!
