### ISSUE TITLE
Add GKE Basic Authentication is enabled query for Terraform

### ISSUE THREAD

**Issue by cx-ruben-silva** [Checkmarx/kics#76]
### Platform
Terraform

### Provider
GCP

### Description
GCP - Google Kubernetes Engine (GKE) Basic Authentication must be disabled, which means the username and password provided in the master_auth block must be empty

**Comment by meldaravaniel** [comment]
@Ruben-Silva I was poking around my kics tf vulnerabilities report, and I initially thought this query was incorrect (maybe based on assuming it's the same for [Ansible](https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_cluster_module.html#parameter-master_auth)?).  According to both [terraform documentation](https://registry.terraform.io/providers/hashicorp/google/4.52.0/docs/resources/container_cluster#master_auth), and my cluster state, the structure of the `master_auth` block is:

```hcl
master_auth {
  client_certificate_config {
    issue_client_certificate = false
  }
}
```

But the Ansible docs are more helpful in this case, stating this is not a thing in clusters using GKE < 1.19.  It seems prudent to keep the query in case folks on old versions are using Kics, and it might be too much work to determine the version since some people may be using variables that aren't defined in the resource itself.  To that end, I think the message should include the affected version.  Also recommend matching the wording of the "must have master auth enabled" query to be more clear.

I've created this PR in case you agree: https://github.com/Checkmarx/kics/pull/6153
